jobs:
  
  weatherService:
    source:
      repository: https://github.com/zhenlei520/Weather.API.git
      branchOrCommit: main
      project: Weather.API/Weather.API.csproj.csproj
    readyStateText: Application started.

  mvcServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/Mvc/Mvc.csproj
    readyStateText: Application started
    waitForExit: false
    variables:
      useNewtonsoftJson: false
    arguments: "{%if useNewtonsoftJson == true %} --useNewtonsoftJson true {% endif %}"
  mapaction:
    source:
      repository: https://github.com/aspnet/Benchmarks.git
      branchOrCommit: main
      project: src/BenchmarksApps/MapAction/MapAction.csproj
    readyStateText: Application started.
